defaults:
  - _self_
  - trainer: trainer
  - network: ffn 
  - trainer/lottery
  - trainer/optimizer
  - trainer/losses
  - data/dataset
  - logging/checkpoint
  - logging/wandb
  - common/common
  - experiment: default


hydra:
  run:
    dir: ${logging.checkpoint.logdir}

  output_subdir: hydra
